name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/sprint-2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install flask requests pytest

      - name: Run tests
        run: |
          cd user-service
          pytest
